### ISSUE TITLE
[Bug]: Updating Recurring Task from Agenda View updates wrong day

### ISSUE THREAD

**Issue by Lankly** [callumalpass/tasknotes#327]
### What's the bug?

I have a recurring task in Agenda View:

<img width="680" height="176" alt="Image" src="https://github.com/user-attachments/assets/83f92127-750b-41fb-b012-193ae4c9775a" />

And when I click on it, it updates for the wrong day:

<img width="702" height="381" alt="Image" src="https://github.com/user-attachments/assets/0b2bbcb5-3fe9-48d9-a6d8-0cb791a76cc9" />

I have to enter the note and manually enter the correct date.

### Which part of TaskNotes is affected?

Agenda View

**Comment by callumalpass** [comment]
Hi @Lankly . Could you please let me know what version you're using? This was a bug in 3.16.0, but should be fixed now in version 3.16.2.

**Comment by LuxBetancourt** [comment]
The Community Plugins page is reporting 3.16.2. I even restarted Obsidian just to be sure.

**Comment by callumalpass** [comment]
OK, thank you! I'll have a look into it. To confirm--you mark a task as complete for today, and it instead marks tomorrow's as complete?

**Comment by callumalpass** [comment]
Could you please update to 3.16.3 and please let me know if that has fixed the issue (I'm not confident that it will have). I really appreciate you taking the time to report this. These timezone issues can be difficult to reproduce, and so I rely a lot on people in different timezones letting me know what they see!

**Comment by LuxBetancourt** [comment]
> OK, thank you! I'll have a look into it. To confirm--you mark a task as complete for today, and it instead marks tomorrow's as complete?

That's correct

> Could you please update to 3.16.3 and please let me know if that has fixed the issue (I'm not confident that it will have). I really appreciate you taking the time to report this. These timezone issues can be difficult to reproduce, and so I rely a lot on people in different timezones letting me know what they see!

Updated and restarted Obsidian. Unfortunately, this issue is still present. My timezone is UTC-04:00.

**Comment by callumalpass** [comment]
This should be fixed in 3.17.0, @Lankly . Please let me know if you're still seeing problems.
